### PR TITLE
Added a new file random-pass-gen.py

### PR DESCRIPTION
**Pull request by tausiq2003**
In this .py file I have added random function from which random
alphanumberic characters are created, which makes the password even
stronger. Adding a memory element and certain encryption and decryption, we can make it a random password more useful to users.
But this is a simple random password generator. This is the solution of #90

### CODE REVIEW

**Comment by tausiq2003** [comment]
Please add this file for hacktoberfest 2021

**Comment by san-coding** [comment]
this PR references #90

**Comment by tausiq2003** [comment]
Yeah

**Comment by tausiq2003** [comment]
Please accept my pull request

**Pull request merged**
